.NVM0
; Generated by Perano Language Compiler

; Function: main
fn_main:
    ; call stdio.Println
    push 53
    syscall print
    push 57
    syscall print
    push 52
    syscall print
    push 54
    syscall print
    push 57
    syscall print
    push 53
    syscall print
    push 54
    syscall print
    push 55
    syscall print
    push 57
    syscall print
    push 48
    syscall print
    push 55
    syscall print
    push 54
    syscall print
    push '
'
    syscall print
    ; Main returns 0 by default
    push 10
    syscall print
    push 0
    syscall exit
    ret

